services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: oh_db
    ports:
      - "3306:3306"
    volumes:
      - /usr/local/var/mysql:/var/lib/mysql